### ISSUE TITLE
Request: increase default scale size of empties

### ISSUE THREAD

**Issue by MxAshUp** [aconz2/blender-instancing-addon#2]
The default empty size of 0.01 seems pretty small, I thought my empties were hidden when I activated the plugin, until I realized the scale was 0.01. If this is intentional to keep it at 0.01, then feel free to close. But I think it would improve the usability.

**Comment by aconz2** [comment]
Thanks for the suggestion, that is totally reasonable. Fixed [here](https://github.com/aconz2/blender-instancing-addon/commit/6997bf509addd741aa49c6644492e8426ae71ab5)
