### ISSUE TITLE
Addon won't install

### ISSUE THREAD

**Issue by PurgeBS** [aconz2/blender-instancing-addon#3]
As requested here is an issue. When I try installing the addon, nothing happens. I've tried this with both the zip and the py file but neither works. Doing an F3 search reveals that it has not been installed. I am using Blender 2.93 LTS on Windows.

It just so happens that I am in the process of manually placing empties at vertices on an object and linking them to those vertices, so an addon like this would be a big help.

** ***Actually the problem isn't your addon at all**. Out of curiosity I opened the file in the script editor and discovered it was about 1700 lines of HTML- very different to the code you wrote. It seems to be that for some reason when I download the zip or right click and save the py file, it instead gives me a bunch of HTML for the GitHub page. I can't be sure if this is a problem with GitHub, Firefox or the various ad blockers and anti malware plugins I use, but it isn't your addon (unless of course somehow HTML has overwritten your code). I cut and pasted the code from the script page and saved that, and it works just as described. Sorry to have bothered you with this.

**Comment by aconz2** [comment]
Ahh that'll do it!

Yeah if you're looking for right click save behavior, I think either:
1) From the repo page, "Code" > Right-click "Download ZIP" > "Save Link as"
2) When viewing `instancing.py`, "Raw", then Right-click anywhere and "Save Page as" (though I'm not sure if Windows will respect the `.py` extension or add its own `.txt` extension. On Linux it does the right thing

Closing this issue but feel free to open another one if it is the addon not working
